pipeline {
    agent {
        docker {
            image 'maven:3.9.6-eclipse-temurin-17'
            args '-v /root/.m2:/root/.m2'
        }
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('achat') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Test') {
            steps {
                dir('achat') {
                    echo 'Aucun test dans le projet → étape Test ignorée'
                    sh 'mvn test -DskipTests'
                }
            }
            post {
                always {
                    echo 'Pas de rapports JUnit (aucun test défini)'
                }
            }
        }

        stage('Archive') {
            steps {
                dir('achat') {
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }
    }

    post {
        success {
            echo 'Build réussi !'
        }
        failure {
            echo 'Build en échec.'
        }
    }
}
